

spring:
  profiles:
    active: prod

  mvc:
   pathmatch:
     matching-strategy: ant_path_matcher
---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database: mysql
      open-in-view: false
      generate-ddl: true
      hibernate:
        ddl-auto: update
      show-sql: true
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omsb2b?characterEncoding=utf8
  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

